default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .static
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/applications/blog/templates/
    - src/applications/hello/templates/
    - src/applications/landing/templates/
    - src/applications/onboarding/templates/
    - src/project/templates/
  HOST: ""
  MODE_DEBUG: true
  MODE_PROFILING: false
  PORT: -1
  PROJECT_NAME: ""
  REQUEST_TTL: 0
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  TEST_BROWSER: ""
  TEST_BROWSER_HEADLESS: true
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  HOST: "localhost"
  PORT: 8000
  REQUEST_TTL: 300
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 1


ci:
  HOST: "localhost"
  PORT: 8000
  REQUEST_TTL: 100
  SECRET_KEY: "1"
  TEST_BROWSER: "chrome"
  WEB_CONCURRENCY: 2


heroku:
  HOST: "tmz-z37.herokuapp.com"
  MODE_DEBUG: false
  REQUEST_TTL: 10
  VENV_SYNTHETIC: true